name: Docker build CI

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ci
        uses: docker/build-push-action@v5
        with:
          file: ci.Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY }}/${{ github.repository }}:ci
