name: Docker build CI

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push cpu-dev
        uses: docker/build-push-action@v3
        with:
          file: cpu.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libtorch-docker:cpu-dev
      -
        name: Build and push cuda-dev
        uses: docker/build-push-action@v3
        with:
          file: cuda.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/libtorch-docker:cuda-dev
